version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13.1
        auth:
          username: guildenstern79
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run tests
  build:
    docker:
      - image: cimg/node:16.13.1
        auth:
          username: guildenstern79
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Build


workflows:
  smartreact:
    jobs:
      - test
      - build
