jobs:
    test:
        docker:
            - image: cimg/node:19.5.0
              auth:
                  username: guildenstern70
                  password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
      - node/install-packages:
            pkg-manager: yarn
      - run:
            command: yarn run test
            name: Run tests
    build:
        docker:
            - image: cimg/node:19.5.0
              auth:
                  username: guildenstern70
                  password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
      - node/install-packages:
            pkg-manager: yarn
      - run:
            command: yarn run build
            name: Build


workflows:
    smartreact:
        jobs:
            - test
            - build
